/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hvv4.hv.calibration;

/**
 *
 * @author yaroslav
 */
public class HVV4HvCalibration extends javax.swing.JFrame {

    /**
     * Creates new form HVV4HvCalibrationMainFrame
     */
    public HVV4HvCalibration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblComPortTitle = new javax.swing.JLabel();
        edtComPortValue = new javax.swing.JTextField();
        btnConnect = new javax.swing.JButton();
        btnDisconnect = new javax.swing.JButton();
        btnTurnOff = new javax.swing.JButton();
        lblPreset = new javax.swing.JLabel();
        edtPreset = new javax.swing.JTextField();
        lblCodeCurrent = new javax.swing.JLabel();
        edtCodeCurrent = new javax.swing.JTextField();
        lblCodeVoltage = new javax.swing.JLabel();
        edtCodeVoltage = new javax.swing.JTextField();
        lblCurrent = new javax.swing.JLabel();
        edtCurrent = new javax.swing.JTextField();
        lblVoltage = new javax.swing.JLabel();
        edtVoltage = new javax.swing.JTextField();
        btnPresetApply = new javax.swing.JButton();
        btnReqCodes = new javax.swing.JButton();
        btnAcceptPoint = new javax.swing.JButton();
        scrlPanePresets = new javax.swing.JScrollPane();
        lstPresets = new javax.swing.JList();
        scrlPaneCodesCurrent = new javax.swing.JScrollPane();
        lstCodesCurrent = new javax.swing.JList();
        scrlPaneCodesVoltage = new javax.swing.JScrollPane();
        lstCodesVoltage = new javax.swing.JList();
        scrlPaneCurrents = new javax.swing.JScrollPane();
        lstCurrents = new javax.swing.JList();
        scrlPaneVoltages = new javax.swing.JScrollPane();
        lstVoltages = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(710, 310));
        setResizable(false);
        getContentPane().setLayout(null);

        lblComPortTitle.setText("COM порт:");
        getContentPane().add(lblComPortTitle);
        lblComPortTitle.setBounds(10, 10, 130, 30);
        getContentPane().add(edtComPortValue);
        edtComPortValue.setBounds(150, 10, 130, 30);

        btnConnect.setText("Соединить");
        getContentPane().add(btnConnect);
        btnConnect.setBounds(290, 10, 130, 30);

        btnDisconnect.setText("Разъединить");
        getContentPane().add(btnDisconnect);
        btnDisconnect.setBounds(430, 10, 130, 30);

        btnTurnOff.setText("Снять HV");
        getContentPane().add(btnTurnOff);
        btnTurnOff.setBounds(570, 10, 130, 30);

        lblPreset.setText("Код уставки:");
        getContentPane().add(lblPreset);
        lblPreset.setBounds(10, 50, 130, 30);
        getContentPane().add(edtPreset);
        edtPreset.setBounds(10, 80, 130, 30);

        lblCodeCurrent.setText("Код тока:");
        getContentPane().add(lblCodeCurrent);
        lblCodeCurrent.setBounds(150, 50, 130, 30);
        getContentPane().add(edtCodeCurrent);
        edtCodeCurrent.setBounds(150, 80, 130, 30);

        lblCodeVoltage.setText("Код напряжения:");
        getContentPane().add(lblCodeVoltage);
        lblCodeVoltage.setBounds(290, 50, 130, 30);
        getContentPane().add(edtCodeVoltage);
        edtCodeVoltage.setBounds(290, 80, 130, 30);

        lblCurrent.setText("Ток, мкА:");
        getContentPane().add(lblCurrent);
        lblCurrent.setBounds(430, 50, 130, 30);
        getContentPane().add(edtCurrent);
        edtCurrent.setBounds(430, 80, 130, 30);

        lblVoltage.setText("Напряжение, В:");
        lblVoltage.setToolTipText("");
        getContentPane().add(lblVoltage);
        lblVoltage.setBounds(570, 50, 130, 30);
        getContentPane().add(edtVoltage);
        edtVoltage.setBounds(570, 80, 130, 30);

        btnPresetApply.setText("Подать");
        getContentPane().add(btnPresetApply);
        btnPresetApply.setBounds(10, 120, 130, 30);

        btnReqCodes.setText("Получить");
        getContentPane().add(btnReqCodes);
        btnReqCodes.setBounds(150, 120, 270, 30);

        btnAcceptPoint.setText("Добавить точку");
        getContentPane().add(btnAcceptPoint);
        btnAcceptPoint.setBounds(430, 120, 270, 30);

        lstPresets.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        scrlPanePresets.setViewportView(lstPresets);

        getContentPane().add(scrlPanePresets);
        scrlPanePresets.setBounds(10, 160, 130, 139);

        lstCodesCurrent.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        scrlPaneCodesCurrent.setViewportView(lstCodesCurrent);

        getContentPane().add(scrlPaneCodesCurrent);
        scrlPaneCodesCurrent.setBounds(150, 160, 130, 139);

        lstCodesVoltage.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        scrlPaneCodesVoltage.setViewportView(lstCodesVoltage);

        getContentPane().add(scrlPaneCodesVoltage);
        scrlPaneCodesVoltage.setBounds(290, 160, 130, 139);

        lstCurrents.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        scrlPaneCurrents.setViewportView(lstCurrents);

        getContentPane().add(scrlPaneCurrents);
        scrlPaneCurrents.setBounds(430, 160, 130, 139);

        lstVoltages.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        scrlPaneVoltages.setViewportView(lstVoltages);

        getContentPane().add(scrlPaneVoltages);
        scrlPaneVoltages.setBounds(570, 160, 130, 139);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HVV4HvCalibration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HVV4HvCalibration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HVV4HvCalibration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HVV4HvCalibration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HVV4HvCalibration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcceptPoint;
    private javax.swing.JButton btnConnect;
    private javax.swing.JButton btnDisconnect;
    private javax.swing.JButton btnPresetApply;
    private javax.swing.JButton btnReqCodes;
    private javax.swing.JButton btnTurnOff;
    private javax.swing.JTextField edtCodeCurrent;
    private javax.swing.JTextField edtCodeVoltage;
    private javax.swing.JTextField edtComPortValue;
    private javax.swing.JTextField edtCurrent;
    private javax.swing.JTextField edtPreset;
    private javax.swing.JTextField edtVoltage;
    private javax.swing.JLabel lblCodeCurrent;
    private javax.swing.JLabel lblCodeVoltage;
    private javax.swing.JLabel lblComPortTitle;
    private javax.swing.JLabel lblCurrent;
    private javax.swing.JLabel lblPreset;
    private javax.swing.JLabel lblVoltage;
    private javax.swing.JList lstCodesCurrent;
    private javax.swing.JList lstCodesVoltage;
    private javax.swing.JList lstCurrents;
    private javax.swing.JList lstPresets;
    private javax.swing.JList lstVoltages;
    private javax.swing.JScrollPane scrlPaneCodesCurrent;
    private javax.swing.JScrollPane scrlPaneCodesVoltage;
    private javax.swing.JScrollPane scrlPaneCurrents;
    private javax.swing.JScrollPane scrlPanePresets;
    private javax.swing.JScrollPane scrlPaneVoltages;
    // End of variables declaration//GEN-END:variables
}
